name = input("이름을 입력하세요: ")
ss_no = input("학번을 입력하세요: ")
dprt = input("학과를 입력하세요: ")
univ = input("학교를 입력하세요: ")

print("<출력>")
print("이름: ", name)
print("학번: ", ss_no)
print("학과: ", dprt)
print("학교: ", univ)